sudo: required
services:
- docker
before_install:
- curl -L https://goss.rocks/install | sudo sh
- docker build -t visibilityspots/jenkins-docker .
script:
- dgoss run --name jenkins-docker -ti visibilityspots/jenkins-docker
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u=visibilityspots -p="$DOCKER_PASSWORD";
  docker push visibilityspots/jenkins-docker; fi
env:
  global:
    secure: OeHi34VEqgRIez11nin0iT9mBH74XuMvFu9KJuZQoi32aRRwusochhB4+o3XrbJu1nWbAiJcwcAkZErZwnDDUx/TtJOps+fFf8UdJexFkBn8o08syrUAN8fKnyrZA5f6tUalii9MuktPdawQilQh+2Yb1HjLIyx00m5L6Z6+FqRFkOr26Am1KLIeRdFgxHXysjKaKTXEAGo2oMLPVrT4PDtBgDvB5r5NLtjdVfql8y5q47otrAa/WgsugSQ6JIyzXVHleoTFJDPtU5v4qN3JzFYS3nYZRlSJ5Pjau+e6GdTRqxXL/z2CGRPwIgZ0/99qw6DLdIyduKhlDqxha4PemeqF0iB+h6r71ZANdxMnOv6tZy3rB7US1TSCmgIvlTS0J2RR/EqPEc6H9EWEXhsUUrlLAPK6Rc+eFCxC5SqNSzb9AH3LQL4aqR4lrArjanL4fSYJDhlmKkmse1nlECOua5YfOIUJDeXBpCeFVMG0tgqLjBGQrIGXkhDrJZuMaLu9lwni9pnBzbzfYg/ucnpI3/+hEuIh+eET6nn3iNZJuC8QMWe2H/GiHIQMEm4ZwcnFVdyPsRwwRN4uoNunmFms4OCldUUxh4Rck/oZh9L4szidGMMqJxk0to4srDhk2isZ4LORdu38415O/xQc4Z9biJXa6UzaT0L6DWPV2AYlxEc=
