sudo: required
services:
- docker
before_install:
- curl -L https://goss.rocks/install | sudo sh
- docker build -t visibilityspots/jenkins-docker .
script:
- dgoss run --name jenkins-docker -ti visibilityspots/jenkins-docker
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u=visibilityspots -p="$DOCKER_PASSWORD";
  docker push visibilityspots/jenkins-docker; fi
env:
  global:
    secure: GVvVc25FvLkx4PkWARiYV9DNOwpEbpuQMSB+9X+eEGgg8VlvYMoflttG4C1KJQfmyZCU4HLhBmF8E6qWPKraI+Oud3X8vHHXO8A0lA4ERsT/R5Uyti4hNMMtie4a867yJIhIFjwidj30Gh+W2yJczTV/cxeTTCWXIWwflkva+oam0WQ+cT5Y2xeYrepXhISRZZozxJif/UmOfndDyiPchbExhxPxmuDoAGmlaiL6zRN/owiaMR01baCIAEwDUPRW4jmCSiCbm0Pd/EPOUCCWdB5Yw57sZR44Q06p2QqAEWMUcUHZ6NZPflyAU7U3+E6t2dxNG3npydRFKINb9McL7BoFY6h/iFbp9KQrCXZkTyHBkNHpC+BvBeoWeN52ToClXTePpORxy/osSNuCCUWaUuHXO57o6mubiOXJq3kJlscHsE6dEHUqxS+bmT3gViS2GCV4bAhACTdVnp6Bi4ud+I7R+e8zYc55pFTOIKW+FsVHAfvBUFltUSietePKPpiC/t5aXuaQQAEsO4jCIbOpwzBPdYYa1MnznNkLD7D7vg4ss5ylUzivJQYwTgUPzB0sfoFw52loYsqIDeZPyNgLmmVhttoiakCExNqxAnw52aQ9asEID4FLWiDPVQRLVz45ahYrr8du4YKp5sF4nMwX4w+q39858BkOvTJzE1zDBGo=
